from utils import enum

nodeNumber = enum("ACTUAL_PARAM", "ADD",         "ADD_ASSIGN",  "ARRAY_VAR",   "ASSIGN_OP",
                "CALL",         "COMPOUND_ST", "CONST_NODE",  "DCL",         "DCL_ITEM",
                "DCL_LIST",     "DCL_SPEC",    "DIV",         "DIV_ASSIGN",  "EQ",
                "ERROR_NODE",   "EXP_ST",      "FORMAL_PARA", "FUNC_DEF",    "FUNC_HEAD",
                "GE",           "GT",          "IDENT",       "IF_ELSE_ST",  "IF_ST",
                "INDEX",        "INT_NODE",    "LE",          "LOGICAL_AND", "LOGICAL_NOT",
                "LOGICAL_OR",   "LT",          "MOD",         "MOD_ASSIGN",  "MUL",
                "MUL_ASSIGN",   "NE",          "NUMBER",      "PARAM_DCL",   "POST_DEC",
                "POST_INC",     "PRE_DEC",     "PRE_INC",     "PROGRAM",     "RETURN_ST",
                "SIMPLE_VAR",   "STAT_LIST",   "SUB",         "SUB_ASSIGN",  "UNARY_MINUS",
                "VOID_NODE",    "WHILE_ST")

nodeName = ["ACTUAL_PARAM", "ADD",         "ADD_ASSIGN",  "ARRAY_VAR",   "ASSIGN_OP",
            "CALL",         "COMPOUND_ST", "CONST_NODE",  "DCL",         "DCL_ITEM",
            "DCL_LIST",     "DCL_SPEC",    "DIV",         "DIV_ASSIGN",  "EQ",
            "ERROR_NODE",   "EXP_ST",      "FORMAL_PARA", "FUNC_DEF",    "FUNC_HEAD",
            "GE",           "GT",          "IDENT",       "IF_ELSE_ST",  "IF_ST",
            "INDEX",        "INT_NODE",    "LE",          "LOGICAL_AND", "LOGICAL_NOT",
            "LOGICAL_OR",   "LT",          "MOD",         "MOD_ASSIGN",  "MUL",
            "MUL_ASSIGN",   "NE",          "NUMBER",      "PARAM_DCL",   "POST_DEC",
            "POST_INC",     "PRE_DEC",     "PRE_INC",     "PROGRAM",     "RETURN_ST",
            "SIMPLE_VAR",   "STAT_LIST",   "SUB",         "SUB_ASSIGN",  "UNARY_MINUS",
            "VOID_NODE",    "WHILE_ST"]

ruleName = [0, nodeNumber.PROGRAM, 0, 0, 0,
            0, nodeNumber.FUNC_DEF, nodeNumber.FUNC_HEAD, nodeNumber.DCL_SPEC, 0,
            0, 0, 0, nodeNumber.CONST_NODE, nodeNumber.INT_NODE,
            nodeNumber.VOID_NODE, 0, nodeNumber.FORMAL_PARA, 0, 0,
            0, 0, nodeNumber.PARAM_DCL, nodeNumber.COMPOUND_ST, nodeNumber.DCL_LIST,
            nodeNumber.DCL_LIST, 0, 0, nodeNumber.DCL, 0,
            0, nodeNumber.DCL_ITEM, nodeNumber.DCL_ITEM, nodeNumber.SIMPLE_VAR, nodeNumber.ARRAY_VAR,
            0, 0, nodeNumber.STAT_LIST, 0, 0,
            0, 0, 0, 0, 0,
            0, nodeNumber.EXP_ST, 0, 0, nodeNumber.IF_ST,
            nodeNumber.IF_ELSE_ST, nodeNumber.WHILE_ST, nodeNumber.RETURN_ST, 0, 0,
            nodeNumber.ASSIGN_OP, nodeNumber.ADD_ASSIGN, nodeNumber.SUB_ASSIGN, nodeNumber.MUL_ASSIGN, nodeNumber.DIV_ASSIGN,
            nodeNumber.MOD_ASSIGN, 0, nodeNumber.LOGICAL_OR, 0, nodeNumber.LOGICAL_AND,
            0, nodeNumber.EQ, nodeNumber.NE, 0, nodeNumber.GT,
            nodeNumber.LT, nodeNumber.GE, nodeNumber.LE, 0, nodeNumber.ADD,
            nodeNumber.SUB, 0, nodeNumber.MUL, nodeNumber.DIV, nodeNumber.MOD,
            0, nodeNumber.UNARY_MINUS, nodeNumber.LOGICAL_NOT, nodeNumber.PRE_INC, nodeNumber.PRE_DEC,
            0, nodeNumber.INDEX, nodeNumber.CALL, nodeNumber.POST_INC, nodeNumber.POST_DEC,
            0, 0, nodeNumber.ACTUAL_PARAM, 0, 0,
            0, 0, 0]
